services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    volumes:
    - "/app/node_modules"
    - "./:/app"

  json-server:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 3500 -w db.json
    ports:
      - "3500:3500"
    volumes:
      - ./data:/data
    restart: always
